### ISSUE TITLE
Improvement in folder structure

### ISSUE THREAD

**Issue by MiSu2002** [leyunn/my-booktracker#1]
There is some issue with the organization of the files and folders. It's hard to guess what's for what. You can group similar files and folders and put them into separate folders. Like create a folder named images and put all the images in it. Also, you can create a parent folder and put everything except readme in it and can change the code accordingly. That'll surely help make it look more organized.

**Comment by leyunn** [comment]
Thanks for the feedback, I updated the file structure.
